SOURCE create_table.sql;
INSERT INTO employees (email, password, fullname) VALUES ('classta@email.edu', 'classta', 'TA CS122B');
SET GLOBAL autocommit=0;
SOURCE ../movie-data.sql;
COMMIT;
SET GLOBAL autocommit=1;
SOURCE price_update.sql;
SOURCE stored-procedure.sql;
SET GLOBAL local_infile=ON;
SELECT * FROM genres;
SELECT COUNT(*) FROM stars;
SELECT COUNT(*) FROM movies;
SELECT COUNT(*) FROM genres_in_movies;
SELECT COUNT(*) FROM stars_in_movies;
