apiVersion: networking.k8s.io/v1             # Specifies Ingress API version
kind: Ingress                                # Defines this resource as an Ingress
metadata:
  name: fabflix-ingress                # Names this Ingress resource
  namespace: default                         # Places this Ingress in the 'default' namespace
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"            # Enables regex matching for paths
    nginx.ingress.kubernetes.io/affinity: "cookie"           # Enables session affinity (sticky sessions)
    nginx.ingress.kubernetes.io/session-cookie-name: "stickounet"  # Defines the name of the session cookie
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"   # Session cookie expires in 2 days
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"   # Max age for the cookie is also 2 days
spec:
  ingressClassName: nginx                     # Use 'nginx' as the Ingress controller
  rules:
    - http:
        paths:
          - path: /fabflix/api/login
            pathType: Prefix                  # Requests beginning with '/api/login' go here
            backend:
              service:
                name: fabflix-login-service    # Name of the Service receiving traffic
                port:
                  number: 8080                # Service port to forward traffic to
          - path: /fabflix/index.html
            pathType: ImplementationSpecific   # Implementation-specific path matching for regex
            backend:
              service:
                name: fabflix-login-service
                port:
                  number: 8080
          - path: /fabflix/js/login.js
            pathType: ImplementationSpecific   # Implementation-specific path matching for regex
            backend:
              service:
                name: fabflix-login-service
                port:
                  number: 8080
          - path: /fabflix/_dashboard/api/login
            pathType: Prefix                  # Requests beginning with '/api/login' go here
            backend:
              service:
                name: fabflix-login-service    # Name of the Service receiving traffic
                port:
                  number: 8080                # Service port to forward traffic to
          - path: /fabflix/_dashboard/index.html
            pathType: ImplementationSpecific   # Implementation-specific path matching for regex
            backend:
              service:
                name: fabflix-login-service
                port:
                  number: 8080
          - path: /fabflix/_dashboard/js/login.js
            pathType: ImplementationSpecific   # Implementation-specific path matching for regex
            backend:
              service:
                name: fabflix-login-service
                port:
                  number: 8080
          - path: /
            pathType: Prefix                  # All other requests matching '/' go here
            backend:
              service:
                name: fabflix-movies-service     # Name of the Service receiving traffic
                port:
                  number: 8080                # Service port to forward traffic to