SELECT "Recreating database structure...";
SOURCE create_table.sql;
SELECT "Importing movie-data.sql...";
SET GLOBAL autocommit=0;
ALTER TABLE movies DISABLE KEYS;
ALTER TABLE stars DISABLE KEYS;
ALTER TABLE genres DISABLE KEYS;
ALTER TABLE stars_in_movies DISABLE KEYS;
ALTER TABLE genres_in_movies DISABLE KEYS;
-- SOURCE ../../fabflix-meta/movie-data.sql;
SOURCE fastdbload.sql;
COMMIT;
ALTER TABLE movies ENABLE KEYS;
ALTER TABLE stars ENABLE KEYS;
ALTER TABLE genres ENABLE KEYS;
ALTER TABLE stars_in_movies ENABLE KEYS;
ALTER TABLE genres_in_movies ENABLE KEYS;
SET GLOBAL autocommit=1;
SELECT "Updating to add pricing info...";
SOURCE price_update.sql;
SELECT "Updating to add stored proc...";
SOURCE stored-procedure.sql;
SET GLOBAL local_infile=ON;
SELECT * FROM genres;
SELECT COUNT(*) FROM stars;
SELECT COUNT(*) FROM movies;
SELECT COUNT(*) FROM genres_in_movies;
SELECT COUNT(*) FROM stars_in_movies;
